services:
  postgres:
    image: postgres:18
    container_name: order-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-orders}
      POSTGRES_USER: ${POSTGRES_USER:-orders}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-orders}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-orders} -d ${POSTGRES_DB:-orders}" ]
      interval: 5s
      timeout: 3s
      retries: 5

  worker-postgres:
    image: postgres:18
    container_name: worker-postgres
    environment:
      POSTGRES_DB: ${WORKER_POSTGRES_DB:-worker}
      POSTGRES_USER: ${WORKER_POSTGRES_USER:-worker}
      POSTGRES_PASSWORD: ${WORKER_POSTGRES_PASSWORD:-worker}
    ports:
      - "5433:5432"
    volumes:
      - worker_pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${WORKER_POSTGRES_USER:-worker} -d ${WORKER_POSTGRES_DB:-worker}" ]
      interval: 5s
      timeout: 3s
      retries: 5

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # --- KRaft: одна нода совмещает роли broker + controller ---
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093

      # --- listeners: 9092 для клиентов, 9093 - внутренний controller-трафик ---
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      # --- для локальной разработки с одной нодой ---
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  pgdata:
  worker_pgdata:
  kafka_data:
